### ISSUE TITLE
while running programm : unfortunately, cubeacon has stopped

### ISSUE THREAD

**Issue by yudhisetiawan** [cubeacon/android-cubeacon-sample#10]
log cat : Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.eyro.cubeacon.CBApp.g' on a null object reference

please help me,

**Comment by alann-maulana** [comment]
Hi @yudhisetiawan 

Thank for your report. There is an issue on our SDK about this error. We will fix it soon. 

Regards.

**Comment by AdhityaRamadhanus** [comment]
I dont know if this is related or not but i keep getting this kind of error recently, it was working fine before. 

09-29 13:13:16.913    2339-2339/rageagainstmachinelearning.queuebeacon E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: rageagainstmachinelearning.queuebeacon, PID: 2339
    java.lang.NullPointerException
            at com.eyro.cubeacon.r$b.handleMessage(SourceFile:370)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5111)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)

I don't know what this function is "at com.eyro.cubeacon.r$b.handleMessage(SourceFile:370)", If i can take a look at your source code maybe i can figure it out (i haven't tried to decompile your sdk, i dont know if it's against the law).

**Comment by alann-maulana** [comment]
Hi @AdhityaRamadhanus 

Thank for your report, we're already on progress on updating our SDK. Please be patient to wait for a new huge update about CubeaconSDK.

Regards.
