### ISSUE TITLE
force close when load data

### ISSUE THREAD

**Issue by intanayu296** [cubeacon/android-cubeacon-sample#13]
03-29 12:00:50.984 11141-11324/com.eyro.cubeacon.demos E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                         Process: com.eyro.cubeacon.demos, PID: 11141
                                                                         java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:841)
                                                                          Caused by: java.lang.NullPointerException
                                                                             at com.eyro.cubeacon.RequestBuilder.execute(RequestBuilder.java:108)
                                                                             at com.eyro.cubeacon.CBLogAnalyticKii.setACLtoBucket(CBLogAnalyticKii.java:166)
                                                                             at com.eyro.cubeacon.CBLogAnalyticKii.requestAdminAccess(CBLogAnalyticKii.java:144)
                                                                             at com.eyro.cubeacon.CBLogAnalyticKii.doInBackground(CBLogAnalyticKii.java:80)
                                                                             at com.eyro.cubeacon.CBLogAnalyticKii.doInBackground(CBLogAnalyticKii.java:31)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                             at java.lang.Thread.run(Thread.java:841) 
03-29 12:00:51.084 11141-11155/com.eyro.cubeacon.demos D/CubeaconSDK: com.eyro.cubeacon.RequestBuilder.execute:180 [RB]statusCode: 200, statusMessage: OK
03-29 12:00:51.094 11141-11155/com.eyro.cubeacon.demos D/CubeaconSDK: com.eyro.cubeacon.RequestBuilder.execute:190 [RB]Response string: {"result":1,"message":"Successfully send."}
03-29 12:00:51.094 11141-11155/com.eyro.cubeacon.demos I/CubeaconSDK: com.eyro.cubeacon.CBAppLogic$2.doInBackground:72 Successfully logged the analytic into Cubeacon...
03-29 12:00:51.244 11141-11193/com.eyro.cubeacon.demos E/CubeaconSDK: com.eyro.cubeacon.ParseCloudBuilder.execute:177 Error request : java.io.FileNotFoundException: https://api.parse.com/1/classes/cb7LcgPyeL

please help

**Comment by alann-maulana** [comment]
Hi @intanayu296 

Thanks for your report, we will fix this soon on next release.

Regards

**Comment by minardid** [comment]
Hi, I think i got same problem.
What is CBLogAnalyticKii? Can we skip that function?
So I can explore more deeper, right now i can't do anything because the null pointer problem.
Thank you.
